### ISSUE TITLE
TTD = Terminal Total Difficulty

### ISSUE THREAD

**Issue by torfbolt** [taxmeifyoucan/predict_ttd#7]
Since TD is the total difficulty of the chain, TTD is an abbreviation for the terminal total difficulty where the merge happens. There are a few places in the repo where it is written as "total terminal difficulty" instead. I don't have access to my PC right now, otherwise I would have written a pull request instead of an issue, sorry for that :)

**Comment by taxmeifyoucan** [comment]
I am aware of this difference and I understand why the wording I chose might sound a bit weird. 

Sometimes `TD` might be used instead of `TTD`, for example `TTD prediction` is always predicting just a TD value. However, I choose to call it TTD to demonstrate it's focused on Merge. After that, there won't be difficulty so the code will be basically useless.

Feel free to open PR if there are places where it creates confusion and should be changed

**Comment by torfbolt** [comment]
It's not about TD vs TTD. The issue is the order of the first two words: TTD means "**terminal total** difficulty", not "total terminal difficulty"

**Comment by taxmeifyoucan** [comment]
Ah, thanks for clarifying! I will fixed all occurrences
